### ISSUE TITLE
Error Instalación Telegram Desktop

### ISSUE THREAD

**Issue by Atheror** [KernelPanicBlog/Script-Post-instalacion#39]
Manjaro KDE

```
--2016-09-26 08:41:24--  https://tdesktop.com/linux
Resolviendo tdesktop.com (tdesktop.com)... 192.186.226.123
Conectando con tdesktop.com (tdesktop.com)[192.186.226.123]:443... conectado.
Petición HTTP enviada, esperando respuesta... 301 Moved Permanently
Localización: https://tdesktop.com/linux/ [siguiendo]
--2016-09-26 08:41:24--  https://tdesktop.com/linux/
Reutilizando la conexión con tdesktop.com:443.
Petición HTTP enviada, esperando respuesta... 302 Moved Temporarily
Localización: https://updates.tdesktop.com/tlinux/tsetup.0.10.8.tar.xz [siguiendo]
--2016-09-26 08:41:25--  https://updates.tdesktop.com/tlinux/tsetup.0.10.8.tar.xz
Resolviendo updates.tdesktop.com (updates.tdesktop.com)... 149.154.167.80
Conectando con updates.tdesktop.com (updates.tdesktop.com)[149.154.167.80]:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 20943856 (20M) [application/octet-stream]
Grabando a: “linux”

linux                            100%[========================================================>]  19,97M  1015KB/s    in 20s     

2016-09-26 08:41:45 (1,01 MB/s) - “linux” guardado [20943856/20943856]

Telegram/
Telegram/Updater
Telegram/Telegram
Traceback (most recent call last):
  File "/usr/bin/mpis", line 78, in main
    core.execute_command(tr.commands, tr.sequentially)
  File "/usr/lib/python3.5/site-packages/mpislib/core.py", line 61, in execute_command
    if subprocess.check_call(cmd) == 0:
  File "/usr/lib/python3.5/subprocess.py", line 576, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: './opt/telegram/Telegram'
```

Se me creó el directorio en **/opt/telegram** con mi usuario como propietario y permisos 0751, contenía los binarios de **Telegram** y **Update**. **MPIS** se ejecutó desde mi directorio **$HOME**  si se estaba buscando por **"./opt/telegram/Telegram"** no lo podría encontrar.

**Comment by hgavidia** [comment]
Este problema es conocido y ya esta solventado, en la version 1.0
hasta la version 0.2a se tenia este problema.
te invito a que clones la rama master y reinstales la version 1.0 
estamos trabajando para que el update llegue a aur pronto
